# Generated by Django 5.2.7 on 2025-10-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swishapp', '0002_category_remove_post_category_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/swish-default-pfp.jpeg', upload_to='profile_pics/'),
        ),
    ]
