# Generated by Django 5.2.7 on 2025-10-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swishapp', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
