# Generated by Django 5.2.7 on 2025-10-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swishapp', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/media/profile_pics/default.jpeg', upload_to='profile_pics/'),
        ),
    ]
