# Generated by Django 5.2.7 on 2025-10-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swishapp', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
