# Generated by Django 5.2.7 on 2025-10-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swishapp', '0008_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked_by',
        ),
    ]
