# Generated by Django 5.2.7 on 2025-11-04 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swishapp', '0013_alter_jobcategory_slug_job_delete_jobpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(default='noemail@swish.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(blank=True, to='swishapp.category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
