# Generated by Django 5.2.7 on 2025-11-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swishapp', '0016_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('follow', 'Follow'), ('message', 'Message'), ('new_post', 'New Post'), ('new_job', 'New Job')], max_length=20),
        ),
    ]
